services:
  go: &go
    tty: true
    stdin_open: true
    build:
      context: .
      target: build
    entrypoint: go
    command: help
    volumes:
      - .:/usr/src/app:delegated
      - gomod:/go/pkg/mod:cached

volumes:
  gomod: {}
