apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: cronitorio/cronitor-kubernetes
      docker:
        dockerfile: Dockerfile


deploy:
  helm:
    releases:
      - name: cronitor-kubernetes
        chartPath: charts/cronitor-kubernetes
        artifactOverrides:
          image: cronitorio/cronitor-kubernetes
        valuesFiles: []
        setValues:
          imagePullPolicy: Never
          credentials:
            secretName: 'cronitor-secret'
            secretKey: 'CRONITOR_API_KEY'
        namespace:  default
        recreatePods: true