{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cronitor-k8s-agent.serviceAccountName" . }}
  labels:
{{ include "cronitor-k8s-agent.labels" . | indent 4 }}
{{- end -}}
