apiVersion: v1
kind: Service
metadata:
  name: {{ include "cronitor-k8s-agent.fullname" . }}-admission-webhook-svc
  labels:
{{ include "cronitor-k8s-agent.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cronitor-k8s-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
