name: Publish Docker image
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Github Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: cronitorio/cronitor-kubernetes/cronitor-kubernetes
          tag_with_ref: true